[package]
name = "a_and_a"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.8"
actix-rt = "2.2.0"
serde = "1.0.117"
serde_json = "1.0.59"
actix-files = "0.6.2"